name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/posthub:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/posthub:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Docker pull
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/posthub:latest

      - name: Docker stop
        run: docker stop posthub || true

      - name: Docker rm
        run: docker rm posthub || true

      - name: Docker run
        run: docker run -d -p 8080:8080 --name posthub ${{ secrets.DOCKER_USERNAME }}/posthub:latest
